package com.cash.ledger.ledger.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.net.Inet4Address;
import java.time.LocalDateTime;

@DynamoDBTable(tableName = "payment")
public class Payment {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Integer id;
    @DynamoDBAttribute
    private Double amount;
    @DynamoDBAttribute
    private LocalDateTime expiredAt;
    @DynamoDBAttribute
    private LocalDateTime paidAt;
    @DynamoDBAttribute
    private String month;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "UserIdIndex")
    @DynamoDBAttribute
    private Integer userId;
    @DynamoDBAttribute
    private LocalDateTime freeTrialEndedOn;
    @DynamoDBAttribute
    private String freeTrialStartedOn;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public LocalDateTime getExpiredAt() {
        return expiredAt;
    }

    public void setExpiredAt(LocalDateTime expiredAt) {
        this.expiredAt = expiredAt;
    }

    public LocalDateTime getPaidAt() {
        return paidAt;
    }

    public void setPaidAt(LocalDateTime paidAt) {
        this.paidAt = paidAt;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public LocalDateTime getFreeTrialEndedOn() {
        return freeTrialEndedOn;
    }

    public void setFreeTrialEndedOn(LocalDateTime freeTrialEndedOn) {
        this.freeTrialEndedOn = freeTrialEndedOn;
    }

    public String getFreeTrialStartedOn() {
        return freeTrialStartedOn;
    }

    public void setFreeTrialStartedOn(String freeTrialStartedOn) {
        this.freeTrialStartedOn = freeTrialStartedOn;
    }
}
