package com.cash.ledger.ledger.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "payment")
public class Payment {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    private String id;
    @DynamoDBAttribute
    private String amount;
    @DynamoDBAttribute
    private String expiredAt;
    @DynamoDBAttribute
    private String paidAt;
    @DynamoDBAttribute
    private Integer month;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "UserIdIndex")
    @DynamoDBAttribute
    private String userId;
    @DynamoDBAttribute
    private String freeTrialEndedOn;
    @DynamoDBAttribute
    private String freeTrialStartedOn;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getExpiredAt() {
        return expiredAt;
    }

    public void setExpiredAt(String expiredAt) {
        this.expiredAt = expiredAt;
    }

    public String getPaidAt() {
        return paidAt;
    }

    public void setPaidAt(String paidAt) {
        this.paidAt = paidAt;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getFreeTrialEndedOn() {
        return freeTrialEndedOn;
    }

    public void setFreeTrialEndedOn(String freeTrialEndedOn) {
        this.freeTrialEndedOn = freeTrialEndedOn;
    }

    public String getFreeTrialStartedOn() {
        return freeTrialStartedOn;
    }

    public void setFreeTrialStartedOn(String freeTrialStartedOn) {
        this.freeTrialStartedOn = freeTrialStartedOn;
    }
}
