package com.cash.ledger.ledger.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "userAccount")
public class UserAccount {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    private String id;

    @DynamoDBAttribute
    private String createdAt;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String fname;

    @DynamoDBAttribute
    private String lname;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "PhoneNumberIndex")
    @DynamoDBAttribute
    private String phoneNumber;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private Integer role;

    @DynamoDBAttribute
    private String lastLogin;

    @DynamoDBAttribute
    private Integer month;

    @DynamoDBAttribute
    private Boolean permanent;

    @DynamoDBAttribute
    private Boolean backupSet;

    @DynamoDBAttribute
    private String lastBackup;

    @DynamoDBAttribute
    private String backupItemsSize;

    @DynamoDBAttribute
    private String transactions;

    @DynamoDBAttribute
    private String categories;

    @DynamoDBAttribute
    private String categoryKeywords;

    @DynamoDBAttribute
    private String categoryMappings;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }


    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getRole() {
        return role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public String getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(String lastLogin) {
        this.lastLogin = lastLogin;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public Boolean getPermanent() {
        return permanent;
    }

    public void setPermanent(Boolean permanent) {
        this.permanent = permanent;
    }

    public Boolean getBackupSet() {
        return backupSet;
    }

    public void setBackupSet(Boolean backupSet) {
        this.backupSet = backupSet;
    }

    public String getLastBackup() {
        return lastBackup;
    }

    public void setLastBackup(String lastBackup) {
        this.lastBackup = lastBackup;
    }

    public String getBackupItemsSize() {
        return backupItemsSize;
    }

    public void setBackupItemsSize(String backupItemsSize) {
        this.backupItemsSize = backupItemsSize;
    }

    public String getTransactions() {
        return transactions;
    }

    public void setTransactions(String transactions) {
        this.transactions = transactions;
    }

    public String getCategories() {
        return categories;
    }

    public void setCategories(String categories) {
        this.categories = categories;
    }

    public String getCategoryKeywords() {
        return categoryKeywords;
    }

    public void setCategoryKeywords(String categoryKeywords) {
        this.categoryKeywords = categoryKeywords;
    }

    public String getCategoryMappings() {
        return categoryMappings;
    }

    public void setCategoryMappings(String categoryMappings) {
        this.categoryMappings = categoryMappings;
    }
}
